export const cups = [
    {
        id: 1,
        status: '圣杯一',
        productName: 'Ace of Cups',
        href: '#',
        imageSrc: '/tarot/Ace-of-Cups.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 2,
        status: '圣杯二',
        productName: 'Two of Cups',
        href: '#',
        imageSrc: '/tarot/Two-of-Cups.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 3,
        status: '圣杯三',
        productName: 'Three of Cups',
        href: '#',
        imageSrc: '/tarot/Three-of-Cups.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 4,
        status: '圣杯四',
        productName: 'Four of Cups',
        href: '#',
        imageSrc: '/tarot/Four-of-Cups.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 5,
        status: '圣杯五',
        productName: 'Five of Cups',
        href: '#',
        imageSrc: '/tarot/Five-of-Cups.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 6,
        status: '圣杯六',
        productName: 'Six of Cups',
        href: '#',
        imageSrc: '/tarot/Six-of-Cups.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 7,
        status: '圣杯七',
        productName: 'Seven of Cups',
        href: '#',
        imageSrc: '/tarot/Seven-of-Cups.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 8,
        status: '圣杯八',
        productName: 'Eight of Cups',
        href: '#',
        imageSrc: '/tarot/Eight-of-Cups.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 9,
        status: '圣杯九',
        productName: 'Nine of Cups',
        href: '#',
        imageSrc: '/tarot/Nine-of-Cups.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 10,
        status: '圣杯十',
        productName: 'Ten of Cups',
        href: '#',
        imageSrc: '/tarot/Ten-of-Cups.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 11,
        status: '圣杯侍从',
        productName: 'Page of Cups',
        href: '#',
        imageSrc: '/tarot/Page-of-Cups.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 12,
        status: '圣杯骑士',
        productName: 'Knight of Cups',
        href: '#',
        imageSrc: '/tarot/Knight-of-Cups.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 13,
        status: '圣杯皇后',
        productName: 'Queen of Cups',
        href: '#',
        imageSrc: '/tarot/Queen-of-Cups.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 14,
        status: '圣杯国王',
        productName: 'King of Cups',
        href: '#',
        imageSrc: '/tarot/King-of-Cups.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    }

]