export const orders = [
    {
        id: 1,
        status: '愚者',
        productName: 'The Fool',
        href: '#',
        imageSrc: '/tarot/The_Fool.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 2,
        status: '魔术师',
        productName: 'The Magician',
        href: '#',
        imageSrc: '/tarot/the-magician.jpg',
        imageAlt: 'Light grey canvas backpack with black handle, zipper, and edge details.',
    },
    {
        id: 3,
        status: '女祭司',
        productName: 'The High Priestess',
        href: '#',
        imageSrc: '/tarot/the-high-priestess.jpg',
        imageAlt: 'Orange canvas cylindrical bag with drawstring top, front zipper pouch, and black shoulder strap.',
    },
    {
        id: 4,
        status: '皇后',
        productName: 'The Empress',
        href: '#',
        imageSrc: '/tarot/the-empress.jpg',
        imageAlt: 'White canvas tote bag with black drawstring liner and white handle.',
    },
    {
        id: 5,
        status: '皇帝',
        productName: 'The Emperor',
        href: '#',
        imageSrc: '/tarot/the-emperor.jpg',
        imageAlt: 'White canvas tote bag with black drawstring liner and white handle.',
    },
    {
        id: 6,
        status: '教皇',
        productName: 'THE HIEROPHANT',
        href: '#',
        imageSrc: '/tarot/the-hierophant.jpg',
        imageAlt: 'White canvas tote bag with black drawstring liner and white handle.',
    },
    {
        id: 7,
        status: '恋人',
        productName: 'The Lovers',
        href: '#',
        imageSrc: '/tarot/the-lovers.jpg',
        imageAlt: 'White canvas tote bag with black drawstring liner and white handle.',
    },
    {
        id: 8,
        status: '战车',
        productName: 'The Chariot',
        href: '#',
        imageSrc: '/tarot/the-chariot.jpg',
        imageAlt: 'White canvas tote bag with black drawstring liner and white handle.',
    },
    {
        id: 9,
        status: '力量',
        productName: 'Strength',
        href: '#',
        imageSrc: '/tarot/strength.jpg',
        imageAlt: 'White canvas tote bag with black drawstring liner and white handle.',
    },
    {
        id: 10,
        status: '隐士',
        productName: 'The Hermit',
        href: '#',
        imageSrc: '/tarot/the-hermit.jpg',
        imageAlt: 'White canvas tote bag with black drawstring liner and white handle.',
    },
    {
        id: 10,
        status: '命运之轮',
        productName: 'The Wheel Of Fortune',
        href: '#',
        imageSrc: '/tarot/the-wheel-of-fortune.jpg',
        imageAlt: 'White canvas tote bag with black drawstring liner and white handle.',
    },
    {
        id: 11,
        status: '正义',
        productName: 'Justice',
        href: '#',
        imageSrc: '/tarot/justice.jpg',
        imageAlt: 'White canvas tote bag with black drawstring liner and white handle.',
    },
    {
        id: 12,
        status: '倒吊人',
        productName: 'Hanged-Man',
        href: '#',
        imageSrc: '/tarot/hanged-man.jpg',
        imageAlt: 'White canvas tote bag with black drawstring liner and white handle.',
    },
    {
        id: 13,
        status: '死神',
        productName: 'Death',
        href: '#',
        imageSrc: '/tarot/death.jpg',
        imageAlt: 'White canvas tote bag with black drawstring liner and white handle.',
    },
    {
        id: 14,
        status: '节制',
        productName: 'Temperance',
        href: '#',
        imageSrc: '/tarot/temperance.jpg',
        imageAlt: 'White canvas tote bag with black drawstring liner and white handle.',
    },
    {
        id: 15,
        status: '恶魔',
        productName: 'The-Devil',
        href: '#',
        imageSrc: '/tarot/The-Devil.jpg',
        imageAlt: 'White canvas tote bag with black drawstring liner and white handle.',
    },
    {
        id: 16,
        status: '塔',
        productName: 'The Tower',
        href: '#',
        imageSrc: '/tarot/The-Tower.jpg',
        imageAlt: 'White canvas tote bag with black drawstring liner and white handle.',
    },
    {
        id: 17,
        status: '星星',
        productName: 'The Star',
        href: '#',
        imageSrc: '/tarot/The-Star.jpg',
        imageAlt: 'White canvas tote bag with black drawstring liner and white handle.',
    },
    {
        id: 18,
        status: '月亮',
        productName: 'The Moon',
        href: '#',
        imageSrc: '/tarot/The-Moon.jpg',
        imageAlt: 'White canvas tote bag with black drawstring liner and white handle.',
    },
    {
        id: 19,
        status: '太阳',
        productName: 'The-Sun',
        href: '#',
        imageSrc: '/tarot/The-Sun.jpg',
        imageAlt: 'White canvas tote bag with black drawstring liner and white handle.',
    },
    {
        id: 20,
        status: '审判',
        productName: 'The Judgement',
        href: '#',
        imageSrc: '/tarot/The-Judgement.jpg',
        imageAlt: 'White canvas tote bag with black drawstring liner and white handle.',
    },
    {
        id: 21,
        status: '世界',
        productName: 'The World',
        href: '#',
        imageSrc: '/tarot/The-World.jpg',
        imageAlt: 'White canvas tote bag with black drawstring liner and white handle.',
    }
]