export const pentacles = [

    {
        id: 1,
        status: '钱币一',
        productName: 'Ace of Pentacles',
        href: '#',
        imageSrc: '/tarot/Ace-of-Pentacles.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 2,
        status: '钱币二',
        productName: 'Two of Pentacles',
        href: '#',
        imageSrc: '/tarot/Two-of-Pentacles.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 3,
        status: '钱币三',
        productName: 'Three of Pentacles',
        href: '#',
        imageSrc: '/tarot/Three-of-Pentacles.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 4,
        status: '钱币四',
        productName: 'Four of Pentacles',
        href: '#',
        imageSrc: '/tarot/Four-of-Pentacles.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 5,
        status: '钱币五',
        productName: 'Five of Pentacles',
        href: '#',
        imageSrc: '/tarot/Five-of-Pentacles.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 6,
        status: '钱币六',
        productName: 'Six of Pentacles',
        href: '#',
        imageSrc: '/tarot/Six-of-Pentacles.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 7,
        status: '钱币七',
        productName: 'Seven of Pentacles',
        href: '#',
        imageSrc: '/tarot/Seven-of-Pentacles.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 8,
        status: '钱币八',
        productName: 'Eight of Pentacles',
        href: '#',
        imageSrc: '/tarot/Eight-of-Pentacles.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 9,
        status: '钱币九',
        productName: 'Nine of Pentacles',
        href: '#',
        imageSrc: '/tarot/Nine-of-Pentacles.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 10,
        status: '钱币十',
        productName: 'Ten of Pentacles',
        href: '#',
        imageSrc: '/tarot/Ten-of-Pentacles.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 11,
        status: '钱币侍从',
        productName: 'Page of Pentacles',
        href: '#',
        imageSrc: '/tarot/Page-of-Pentacles.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 12,
        status: '钱币骑士',
        productName: 'Knight of Pentacles',
        href: '#',
        imageSrc: '/tarot/Knight-of-Pentacles.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 13,
        status: '钱币皇后',
        productName: 'Queen of Pentacles',
        href: '#',
        imageSrc: '/tarot/Queen-of-Pentacles.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 14,
        status: '钱币国王',
        productName: 'King of Pentacles',
        href: '#',
        imageSrc: '/tarot/King-of-Pentacles.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },



]