export const swords = [

    {
        id: 1,
        status: '宝剑一',
        productName: 'Ace of Swords',
        href: '#',
        imageSrc: '/tarot/Ace-of-Swords.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 2,
        status: '宝剑二',
        productName: 'Two of Swords',
        href: '#',
        imageSrc: '/tarot/Two-of-Swords.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 3,
        status: '宝剑三',
        productName: 'Three of Swords',
        href: '#',
        imageSrc: '/tarot/Three-of-Swords.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 4,
        status: '宝剑四',
        productName: 'Four of Swords',
        href: '#',
        imageSrc: '/tarot/Four-of-Swords.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 5,
        status: '宝剑五',
        productName: 'Five of Swords',
        href: '#',
        imageSrc: '/tarot/Five-of-Swords.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 6,
        status: '宝剑六',
        productName: 'Six of Swords',
        href: '#',
        imageSrc: '/tarot/Six-of-Swords.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 7,
        status: '宝剑七',
        productName: 'Seven of Swords',
        href: '#',
        imageSrc: '/tarot/Seven-of-Swords.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 8,
        status: '宝剑八',
        productName: 'Eight of Swords',
        href: '#',
        imageSrc: '/tarot/Eight-of-Swords.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 9,
        status: '宝剑九',
        productName: 'Nine of Swords',
        href: '#',
        imageSrc: '/tarot/Nine-of-Swords.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 10,
        status: '宝剑十',
        productName: 'Ten of Swords',
        href: '#',
        imageSrc: '/tarot/Ten-of-Swords.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 11,
        status: '宝剑侍从',
        productName: 'Page of Swords',
        href: '#',
        imageSrc: '/tarot/Page-of-Swords.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 12,
        status: '宝剑骑士',
        productName: 'Knight of Swords',
        href: '#',
        imageSrc: '/tarot/Knight-of-Swords.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 13,
        status: '宝剑皇后',
        productName: 'Queen of Swords',
        href: '#',
        imageSrc: '/tarot/Queen-of-Swords.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 14,
        status: '宝剑国王',
        productName: 'King of Swords',
        href: '#',
        imageSrc: '/tarot/King-of-Swords.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
]