export const wands = [
    {
        id: 1,
        status: '权杖一',
        productName: 'Ace of Wands',
        href: '#',
        imageSrc: '/tarot/Ace-of-Wands.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 2,
        status: '权杖二',
        productName: 'Two of Wands',
        href: '#',
        imageSrc: '/tarot/Two-of-Wands.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 3,
        status: '权杖三',
        productName: 'Three of Wands',
        href: '#',
        imageSrc: '/tarot/Three-of-Wands.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 4,
        status: '权杖四',
        productName: 'Four of Wands',
        href: '#',
        imageSrc: '/tarot/Four-of-Wands.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 5,
        status: '权杖五',
        productName: 'Five of Wands',
        href: '#',
        imageSrc: '/tarot/Five-of-Wands.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 6,
        status: '权杖六',
        productName: 'Six of Wands',
        href: '#',
        imageSrc: '/tarot/Six-of-Wands.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 7,
        status: '权杖七',
        productName: 'Seven of Wands',
        href: '#',
        imageSrc: '/tarot/seven-of-Wands.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 8,
        status: '权杖八',
        productName: 'Eight of Wands',
        href: '#',
        imageSrc: '/tarot/Eight-of-Wands.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 9,
        status: '权杖九',
        productName: 'Nine of Wands',
        href: '#',
        imageSrc: '/tarot/Nine-of-Wands.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },
    {
        id: 10,
        status: '权杖十',
        productName: 'Ten of Wands',
        href: '#',
        imageSrc: '/tarot/Ten-of-Wands.jpg',
        imageAlt: 'Black fabric shoe bag with zipper around 3 sides, holding pair of white sneakers.',
    },

]